# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'


steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m venv antenv
    source antenv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  workingDirectory: .
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    verbose: true # (no value); this input is optional


/*- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    ConnectedServiceName: 'devops-sp'
    appType: 'webAppLinux'
    WebAppName: 'labpyapp'
    RuntimeStack: 'PYTHON|3.6'
    StartupCommand: 'gunicorn --bind=0.0.0.0 --workers=4 startup:app'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
*/